apiVersion: apps/v1
kind: Deployment
metadata:
  name: news-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: news-app
  template:
    metadata:
      labels:
        app: news-app
    spec:
      containers:
      - name: news-app
        image: aneesh292002/news-app:latest
        ports:
        - containerPort: 5000

        env:
        - name: DB_HOST
          value: "newsdb.xxxxxx.ap-south-1.rds.amazonaws.com"

        - name: DB_USER
          value: "admin"

        - name: DB_PASSWORD
          value: "Devops123"

        - name: DB_NAME
          value: "newsdb"
